---
title: "Auto Sales vs Population: 1967 - 2020"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(scales)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```
```{r}
rm(list=ls())
df <- read_csv("./sales_pop_ratio.csv")
```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Auto Sales Per Capita

```{r}
df |> ggplot() + geom_area(aes(x=year,y=sales_pop,fill='red'))
```

### Number of Autos per Capita.
If we divide population (by year) by number of autos sold (by year), we get the number of autos per capita. 

```{r}
df |> ggplot() + geom_area(aes(x=year,y=pop_sales,fill='blue'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Auto Sales by Year

```{r}
df |> ggplot() + geom_area(aes(x=year,y=sales,fill='yellow' )) +
  scale_y_continuous(labels= comma)
```

### Population by Year

```{r}
df |> ggplot() + geom_area(aes(x=year,y=population,fill='green')) +
  scale_y_continuous(labels= comma)
```

